<a href="https://colab.research.google.com/github/Ynajooje/ProjetoCDZ/blob/main/aula1alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import pandas as pd

In [109]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [110]:
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [111]:
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [112]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [113]:
df.shape

(133349, 11)

In [114]:
linhas, colunas = df.shape [0], df.shape [1]
print ("linhas:", linhas)
print ("colunas:", colunas)

linhas: 133349
colunas: 11

In [115]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [116]:
# Create a dictionary with the current column names and their Portuguese translations
new_column_names = {
    'work_year': 'ano',
    'experience_level': 'nivel_experiencia',
    'employment_type': 'tipo_emprego',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'salario_em_usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'localizacao_empresa',
    'company_size': 'porte_empresa'
}

# Rename the columns using the dictionary
df.rename(columns=new_column_names, inplace=True)

# Display the updated column names to confirm the changes
display(df.columns)

Index(['ano', 'nivel_experiencia', 'tipo_emprego', 'cargo', 'salario', 'moeda',
       'salario_em_usd', 'residencia', 'remoto', 'localizacao_empresa',
       'porte_empresa'],
      dtype='object')

In [117]:
df["nivel_experiencia"].value_counts()

nivel_experiencia
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [118]:
df["tipo_emprego"].value_counts()

tipo_emprego
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [119]:
df["remoto"].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [120]:
# Create a dictionary to map the English experience levels to Portuguese
experience_level_map = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Júnior',
    'EX': 'Executivo'
}

# Apply the mapping to the 'nivel_experiencia' column
df['nivel_experiencia'] = df['nivel_experiencia'].replace(experience_level_map)

# Display the updated value counts to confirm the changes
display(df['nivel_experiencia'].value_counts())

nivel_experiencia
Senior       77241
Pleno        40465
Júnior       12443
Executivo     3200
Name: count, dtype: int64

In [121]:
# Create a dictionary to map the English employment types to Portuguese
employment_type_map = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelancer'
}

# Apply the mapping to the 'tipo_emprego' column using replace
df['tipo_emprego'] = df['tipo_emprego'].replace(employment_type_map)

# Display the updated value counts to confirm the changes
display(df['tipo_emprego'].value_counts())

tipo_emprego
Tempo Integral    132563
Contrato             394
Tempo Parcial        376
Freelancer            16
Name: count, dtype: int64

In [122]:
# Create a dictionary to map the remote ratio to Portuguese terms
remote_map = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

# Apply the mapping to the 'remoto' column using replace
df['remoto'] = df['remoto'].replace(remote_map)

# Display the updated value counts to confirm the changes
display(df['remoto'].value_counts())

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [123]:
df.head()

,ano,nivel_experiencia,tipo_emprego,cargo,salario,moeda,salario_em_usd,residencia,remoto,localizacao_empresa,porte_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M
4,2025.0,Júnior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M

In [124]:
df.describe (include="object")

,nivel_experiencia,tipo_emprego,cargo,moeda,residencia,remoto,localizacao_empresa,porte_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Tempo Integral,Data Scientist,USD,US,Presencial,US,M
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [125]:
df.head()

,ano,nivel_experiencia,tipo_emprego,cargo,salario,moeda,salario_em_usd,residencia,remoto,localizacao_empresa,porte_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M
4,2025.0,Júnior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M

In [126]:
df.isnull().sum()

ano                    10
nivel_experiencia       0
tipo_emprego            0
cargo                   0
salario                 0
moeda                   0
salario_em_usd          0
residencia              0
remoto                  0
localizacao_empresa     0
porte_empresa           0
dtype: int64

In [127]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [128]:
df[df.isnull().any(axis=1)]

,ano,nivel_experiencia,tipo_emprego,cargo,salario,moeda,salario_em_usd,residencia,remoto,localizacao_empresa,porte_empresa
5588,NaN,Senior,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,M
59692,NaN,Pleno,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,M
59710,NaN,Júnior,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,M
59759,NaN,Senior,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,M
59789,NaN,Senior,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,M
131000,NaN,Senior,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,M
131006,NaN,Senior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,M
133054,NaN,Júnior,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,L
133281,NaN,Pleno,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,L
133317,NaN,Pleno,Tempo Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,L

In [129]:
import numpy as np

In [130]:
#Criação de um dataframe teste para teste
df_salarios=pd.DataFrame({
    'nome': ["Ana Julia", "João", "Ana Cristina", "Julio", 'Klara'],
    'salario': [4000, np.nan, 3000, np.nan, 1000000]

    })
# Calcula a média salarial e substitui os nulos pela média e arredonda os valores
df_salarios['salario_media'] = df_salarios ['salario'].fillna(df_salarios['salario'].mean().round(2))
# Calcula a mediana e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios ['salario'].fillna(df_salarios['salario'].median())
df_salarios

           nome    salario  salario_media  salario_mediana
0     Ana Julia     4000.0        4000.00           4000.0
1          João        NaN      335666.67           4000.0
2  Ana Cristina     3000.0        3000.00           3000.0
3         Julio        NaN      335666.67           4000.0
4         Klara  1000000.0     1000000.00        1000000.0

In [131]:
df_temperaturas= pd.DataFrame ({
   'dia': ["Segunda", "Terça", "Quarta", "Quinta", 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas ["preenchido_ffill"] = df_temperaturas ["Temperatura"].ffill()
df_temperaturas

       dia  Temperatura  preenchido_ffill
0  Segunda         30.0              30.0
1    Terça          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [132]:
df_temperaturas= pd.DataFrame ({
   'dia': ["Segunda", "Terça", "Quarta", "Quinta", 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas ["preenchido_bffill"] = df_temperaturas ["Temperatura"].bfill()
df_temperaturas

       dia  Temperatura  preenchido_bffill
0  Segunda         30.0               30.0
1    Terça          NaN               28.0
2   Quarta          NaN               28.0
3   Quinta         28.0               28.0
4    Sexta         27.0               27.0

In [133]:
df_cidades = pd.DataFrame({
    'nome': ["Ana Julia", "João", "Ana Cristina", "Julio", 'Klara'],
    'Cidade': ["São Paulo", np.nan, "Distrito federal", np.nan, "Belém" ]
})

df_cidades['cidade_preenchida'] = df_cidades["Cidade"].fillna("nao informado") # Corrigido a sintaxe para criar a nova coluna
display(df_cidades) # Adicionado display para mostrar o resultado

           nome            Cidade cidade_preenchida
0     Ana Julia         São Paulo         São Paulo
1          João               NaN     nao informado
2  Ana Cristina  Distrito federal  Distrito federal
3         Julio               NaN     nao informado
4         Klara             Belém             Belém

In [134]:
df_limpo = df.dropna()
df_limpo.isnull().sum()

ano                    0
nivel_experiencia      0
tipo_emprego           0
cargo                  0
salario                0
moeda                  0
salario_em_usd         0
residencia             0
remoto                 0
localizacao_empresa    0
porte_empresa          0
dtype: int64

In [138]:
df_limpo.head()

,ano,nivel_experiencia,tipo_emprego,cargo,salario,moeda,salario_em_usd,residencia,remoto,localizacao_empresa,porte_empresa
0,2025,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M
1,2025,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M
2,2025,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M
3,2025,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M
4,2025,Júnior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M

In [139]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ano                  133339 non-null  int64
 1   nivel_experiencia    133339 non-null  object
 2   tipo_emprego         133339 non-null  object
 3   cargo                133339 non-null  object
 4   salario              133339 non-null  int64
 5   moeda                133339 non-null  object
 6   salario_em_usd       133339 non-null  int64
 7   residencia           133339 non-null  object
 8   remoto               133339 non-null  object
 9   localizacao_empresa  133339 non-null  object
 10  porte_empresa        133339 non-null  object
dtypes: int64(3), object(8)
memory usage: 12.2+ MB

In [137]:
df_limpo = df_limpo.assign(ano= df_limpo ['ano'].astype('int64'))